Repository googleworkspace/.github, pull requests merged in 2022-08, with the labels that each got.

#7 chore: Add and sync super-linter configs
  .github/sync-files-all.yml
  sync-files/defaults/.github/linters/.htmlhintrc
  sync-files/defaults/.github/linters/.yaml-lint.yml
  sync-files/defaults/.github/linters/sun_checks.xml
Labels: yaml

#9 feat: add workflow to show badges on README
  .github/workflows/workflows.sh
  .github/workflows/workflows.yml
Labels: shell

#13 chore: minor delint/reformatting from superlinter
  SECURITY.md
  sync-files/defaults/.github/linters/sun_checks.xml
  sync-files/defaults/.github/workflows/automation.yml
Labels: yaml

#12 fix: Delint (shellcheck) + fix match pattern.
  .github/workflows/workflows.sh
  README.md
Labels: markdown
